#!/bin/bash

# Variables
#----------
begining="#-arx-pacman-mirrors-multilib-begin"
ending="#-arx-pacman-mirrors-multilib-end"

# Delete arx pacman mirrors multilib from pacman.conf
#----------------------------------------------------
sudo sed -i "/^$begining/,/^$ending/{/^$begining/!{/^$ending/!d}}" /etc/pacman.conf
sudo sed -i "/$begining/d" /etc/pacman.conf
sudo sed -i "/$ending/d" /etc/pacman.conf

echo -e "Pacman mirrors multilib disabled"
