#!/bin/bash

# 1. Backup existing profile
#------------------------------
if [  -f "$HOME/.profile"  ]; then
    cp "$HOME/.profile" "$HOME/.profile.arxbak" 
fi


# 2. Remove existing profile
#------------------------------
if [  -f "$HOME/.profile"  ]; then
    rm "$HOME/.profile"
fi

# 3. Restore (link) profile from dofiles
#------------------------------------------------
ln -s "$arxdotdir/.profile" "$HOME/.profile"

