#!/bin/bash

# 1. Backup existing pacman.conf
# if it wasn't done earlier
#-------------------------------
if [  -f /etc/pacman.conf && ! -f /etc/pacman.conf.arxbak ]; then
    sudo cp /etc/pacman.conf /etc/pacman.conf.arxbak
fi 

# 2. Append needed settings
#--------------------------
text="
# Pacman configuration options
# ADDED BY SETUP SCRIPT
# ===============================
[options]
Color
ParallelDownloads = 10
#================================
"
echo -e " $text" | sudo tee -a /etc/pacman.conf > /dev/null
