#!/bin/bash

directories=(
    "$HOME/.config"
    "$HOME/.local/share" 
    "$HOME/.local/state"
    "$HOME/.local/bin"
    )

for dir in "${directories[@]}"; do
  if [ ! -d "$dir" ]; then
    mkdir -p "$dir"
  fi
done