#!/bin/bash

# 1. Backup existing pacman.conf
# if it wasn't done earlier
#-------------------------------
if [[  -f /etc/pacman.conf && ! -f /etc/pacman.conf.arxbak ]]; then
    sudo cp /etc/pacman.conf /etc/pacman.conf.arxbak
fi 

# 2. Append chaotic-aur repository
#---------------------------------
sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key 3056513887B78AEB
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

text="
# Pacman CHAOTIC AUR repository
# ADDED BY SETUP SCRIPT
# ===============================
[chaotic-aur]
Include = /etc/pacman.d/chaotic-mirrorlist
#================================
"
echo -e " $text" | sudo tee -a /etc/pacman.conf > /dev/null
sudo pacman -Syu --noconfirm
