#!/bin/bash

# 1. Backup existing pacman.conf
# if it wasn't done earlier
#-------------------------------
if [[  -f /etc/pacman.conf && ! -f /etc/pacman.conf.arxbak ]]; then
    sudo cp /etc/pacman.conf /etc/pacman.conf.arxbak
fi 

# 2. Append multilib repository
#------------------------------
text="
# Pacman MULTILIB repository
# ADDED BY SETUP SCRIPT
# ===============================
[multilib]
Include = /etc/pacman.d/mirrorlist
#================================
"
echo -e " $text" | sudo tee -a /etc/pacman.conf > /dev/null
sudo pacman -Syu --noconfirm
