#!/bin/bash

# 1. Backup existing pacman.conf
# if it wasn't done earlier
#-------------------------------
if [[  -f /etc/pacman.conf && ! -f /etc/pacman.conf.arxbak ]]; then
    sudo cp /etc/pacman.conf /etc/pacman.conf.arxbak
fi 

# 2. Append needed settings
#--------------------------
text="
#-arx-pacman-settings-begin
# ===============================
[options]
Color
VerbosePkgLists
ParallelDownloads = 10
#================================
#-arx-pacman-settings-end
"
echo -e " $text" | sudo tee -a /etc/pacman.conf > /dev/null
