#!/bin/bash

# MANUAL OPERATIONS
#
# Setup script requiers sudo vim and git to work.
# Next add your user to the wheel group, install 
# dependensies and configure sudo.

# 1. Login as root. Check if your regular user is a member of the wheel group:
# -----------
#    groups $USER
# -----------
# If there is wheel in output, go to step 2. Else run:
# -----------
#     useadd -aG wheel $USER
# -----------

# 2. Install sudo, vim and git:
# ------------
#     pacman -S sudo vim git
# ------------

# 3. Cnfigure sudo:
# ------------
#    vim /etc/sudoers
# ------------
# Uncomment line with %wheel !!!PASTE FULL LINE!!!
# Type :wq! to save changes and quit vim.

# 4. Log uot and login as your user. Check if sudo works
#-------------
#    sudo pacman -Syu
# ------------
# If it doesn't work, reboot system.

# 5. Login as your user.
# Make a directory .config and cd to it
# ------------
#     mkdir .config
#     cd .config
# ------------

# 6. Clone dotfiles repository
# ------------
#     git clone !!!ADD LINK HERE!!!
# ------------

# 7. Make all script executable:
# ------------
#     chmod +x arch-setup/scripts/*
#  -----------


# 8. Cd to dotfiles/scripts and run this setup script
# ------------
#     cd arch-setup/scripts
#     .00-setup
# ------------

# AUTOMATIC OPERATIONS
#
# View and comment/uncomment needed parts.
# Also review and edit scripts themeselves.

# 01. BASE
./01-00-pacman-settings
./01-01-pacman-mirrors-multilib
#./01-02-pacman-mirrors-chaotic
./01-03-locales
./01-04-man-db
./01-05-htop
./01-06-inxi
./01-07-lvm2
./01-08-wget
./01-09-ncdu
./01-10-rsync
./01-11-tree 
./01-12-inagemagick
./01-13-mc
./01-14-ranger
./01-15-archivers

# 02 Dotfiles
# stow
# rsync

# mc
# bashrc
# zsh
# tmux
# user-dirs
# profile
# aliases
# xresources
# vim


# fzf
# exa 
# cryfs



# 03 SYSTEM SERVICES
#----------------------
# nfs-utils
# wireguard
# samba
# tlp 
# syncthing
# ssh



# APPS
#----------------------
# digikam
# color chooser
# keepassxc
# mpv
# viewnior
# chromium
# firefox
# pdf
# rapid photo downloader
# qutebrowser
# qbittorrent
# obsidian
# doublecommander
# libreoffice
# darktable
# gimp
# inkscape
# blender
# freecad
# homebank
# calibre
# telegram
# vinagre
# baobab
# virt-manager libvirt
# wine
# local/share/applications
# kitty

# APEARANCE
#-----------------------
# fonts
# papirus-icons


# FLATPAK
#------------------------
# flatpak
# freeplane flatpak
# vscode flatpak

# DE
#----------------------
# gnome
# kde

# # WM
#---------------------
# batsignal
# rofi
# polkit
# sxhkd
# qtile
# xorg
# xorg-xinit
# picom
# pulseaudio
# pamixer
# nitrogen
# neofetch
# i3lock
# conky
# tint2
# dunst
# scrot
# xss-lock

# AUR
#------------------------
# yay
# light
# jumpapp
# xidlehook


# 10. END
echo -e "Arch Setup Done"

