#!/bin/bash

sudo pacman -S syncthing --noconfirm
sudo sh -c 'echo 204800 > /proc/sys/fs/inotify/max_user_watches'
echo "fs.inotify.max_user_watches=204800" | sudo tee -a /etc/sysctl.conf
sleep 5
sudo systemctl enable syncthig@$USER.service
