#!/bin/bash
source="../dots"

destination="$HOME"

files=(
    ".bashrc"
    ".profile"
    ".zshenv"
    ".config/zsh/.zshrc" 
    ".config/aliases" 
    ".config/starship/starship.toml" 
    )

for file in "${files[@]}"; do
     rsync -avz $source/$file $destination/$file
done