#!/bin/bash

sudo pacman -S batsignal --noconfirm
# sudo pacman -S xfce4-power-manager --noconfirm
# sudo pacman -S mate-power-manager --noconfirm
# sudo pacman -S lxqt-power-management --noconfirm
sudo pacman -S i3lock --noconfirm
sudo pacman -S xss-lock --noconfirm

