#!/bin/bash

# 1. Install conky
#---------------
sudo pacman -S conky --noconfirm

# 3. Create needed directories
#-----------------------------
directories=(
    "$HOME/dnl/test/destination/conky"
    "$HOME/dnl/test/destination/conky/scripts"
    )

for dir in "${directories[@]}"; do
  if [ ! -d "$dir" ]; then
    mkdir -p "$dir"
  fi
done

# 3. Backup existing conky config
#------------------------------
exist_files=(
    $(find $HOME/.config/conky  -type f)
    )
for file in "${exist_files[@]}"; do
  if [  -f "$file" ]; then
    cp "$file" "$file".arxbak
  fi 
done

# 4. Remove existing conky config
#------------------------------
for file in "${exist_files[@]}"; do
  if [  -f "$file" ]; then
    rm "$file"
  fi
done

# 5. Restore (link) conky config files from dofiles
#------------------------------------------------
target_files1=(
    $(find $arxdotdir/.config/conky -maxdepth 1 -type f -printf "%f\n")
    )

for file in "${target_files1[@]}"; do
   if [  -f "$file" ]; then   
      ln -s "$arxdotdir/.config/conky$file" "$HOME/.config/conky/$file"
   fi   
done

target_files2=(
    $(find $arxdotdir/.config/conky/scripts -maxdepth 1 -type f -printf "%f\n")
    )

for file in "${target_files2[@]}"; do
   if [  -f "$file" ]; then   
      ln -s "$arxdotdir/.config/conky/scripts/$file" "$HOME/.config/conky/scripts/$file"
   fi   
done
